production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  cleanup_orphaned_blobs:
    class: CleanupOrphanedBlobsJob
    schedule: every 30 minutes

  enforce_retention_policy:
    class: EnforceRetentionPolicyJob
    schedule: every day at 3am

  prune_old_events:
    class: PruneOldEventsJob
    schedule: every day at 4am
